name: build and test

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        converted_to_draft,
      ]
    branches: [master]

jobs:
  test_trinity:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: trinity
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: make test NAME=trinity
    env:
      IMAGE_NAME: trinity
